# DataBase
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.url=${POSTGRES_URL}

# Infra/Security
infra.security.jwt=${JWT_SECRET}

# Email
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_TTLS}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# Logs e Observabilidade
management.metrics.enable.jvm=true
management.metrics.enable.system=true
management.metrics.enable.tomcat=true
management.metrics.enable.logback=true
management.metrics.tags.application=Pernambox-Backend
management.metrics.tags.environment=producao