spring.config.import=optional:file:.env[.properties]

# Logs e Observabilidade
management.metrics.enable.jvm=true
management.metrics.enable.system=true
management.metrics.enable.tomcat=true
management.metrics.enable.logback=true
management.metrics.tags.application=Pernambox-Backend
management.metrics.tags.environment=development