spring.application.name=Pernambox

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.boot.autoconfigure.web=DEBUG

spring.jpa.database=postgresql

management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.enabled=true

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}