spring.application.name=Pernambox

spring.config.import=optional:file:.env[.properties]

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.boot.autoconfigure.web=DEBUG

spring.jpa.database=postgresql