-- Extensão para gerar UUIDs automaticamente
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE endereco
(
    ID          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NUMERO      INT NOT NULL,
    RUA         VARCHAR(255) NOT NULL,
    BAIRRO      VARCHAR(255) NOT NULL,
    MUNICIPIO   VARCHAR(255) NOT NULL,
    ESTADO      VARCHAR(255) NOT NULL,
    CEP         VARCHAR(9),
    COMPLEMENTO VARCHAR (255)
);

CREATE TABLE polo
(
    ID              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NOME            VARCHAR(150) NOT NULL,
    FK_ENDERECO_ID  UUID NOT NULL,
    CONSTRAINT      FK_ENDERECO_ID FOREIGN KEY (FK_ENDERECO_ID)
    REFERENCES      endereco (ID) ON DELETE CASCADE
);

CREATE TYPE tipo_permissao AS ENUM ('ADM_GERAL','ADM_POLO','FUNCIONARIO');

CREATE TABLE usuario
(
    ID          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NOME        VARCHAR(255) NOT NULL,
    CPF         VARCHAR(14)  NOT NULL UNIQUE,
    EMAIL       VARCHAR(255) NOT NULL UNIQUE,
    TELEFONE    VARCHAR(14),
    SENHA       VARCHAR(255) NOT NULL,
    PERMISSAO   tipo_permissao NOT NULL DEFAULT 'FUNCIONARIO',
    FK_POLO_ID  UUID NOT NULL,
    CONSTRAINT  FK_POLO_ID FOREIGN KEY (FK_POLO_ID)
    REFERENCES  polo (ID) ON DELETE CASCADE
);

CREATE TYPE tipo_status AS ENUM ('ESTAVEL','INSTAVEL','CRITICO');
CREATE TYPE tipo_categoria AS ENUM ('EPI','FERRAMENTAS','HIGIENICOS','SAUDE','ALIMENTACAO','OUTROS');

CREATE TABLE equipamento
(
    ID          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    QUANTIDADE  BIGINT NOT NULL,
    STATUS      tipo_status NOT NULL,
    CATEGORIA   tipo_categoria NOT NULL DEFAULT 'OUTROS',
    QTD_EM_USO  BIGINT NOT NULL DEFAULT 0,
    DESCRICAO   VARCHAR(255) NOT NULL,
    FK_POLO_ID  UUID NOT NULL,
    CONSTRAINT  FK_POLO_ID FOREIGN KEY (FK_POLO_ID)
    REFERENCES  polo (ID) ON DELETE CASCADE
);

CREATE TABLE recurso
(
    ID          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    DESCRICAO   VARCHAR(255) NOT NULL,
    STATUS      tipo_status NOT NULL,
    QUANTIDADE  BIGINT NOT NULL,
    VALIDADE    TIMESTAMP NOT NULL,
    CATEGORIA   tipo_categoria NOT NULL DEFAULT 'OUTROS',
    FK_POLO_ID  UUID NOT NULL,
    CONSTRAINT  FK_POLO_ID FOREIGN KEY (FK_POLO_ID)
    REFERENCES  polo (ID) ON DELETE CASCADE
);

CREATE TABLE produto
(
    ID          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    VALIDADE    TIMESTAMP NOT NULL,
    QUANTIDADE  BIGINT NOT NULL,
    GTIN        INT NOT NULL,
    DESCRICAO   VARCHAR(255) NOT NULL
);

CREATE TABLE recurso_produto
(
    FK_PRODUTO_ID   UUID NOT NULL,
    FK_RECURSO_ID   UUID NOT NULL,
    CONSTRAINT      FK_PRODUTO_ID FOREIGN KEY (FK_PRODUTO_ID)
    REFERENCES      produto (ID) ON DELETE CASCADE,
    CONSTRAINT      FK_RECURSO_ID FOREIGN KEY (FK_RECURSO_ID)
    REFERENCES      recurso (ID) ON DELETE CASCADE
);

CREATE TYPE tipo_alteracao AS ENUM ('CREATE','UPDATE','DELETE');
CREATE TYPE alvo_alteracao AS ENUM ('ENDERECO','POLO','USUARIO','PRODUTO','RECURSO','EQUIPAMENTO','RECURSO_PRODUTO','ORIGEM');

CREATE TABLE alteracoes
(
    ID              SERIAL PRIMARY KEY,
    TIPO_ALTERACAO  tipo_alteracao NOT NULL,
    DATA_ALTERACAO  TIMESTAMP NOT NULL,
    ALVO_ALTERACAO  alvo_alteracao NOT NULL,
    DESCRICAO       VARCHAR(255) NOT NULL,
    FK_ALVO_ID      UUID NOT NULL,
    FK_POLO_ID      UUID NOT NULL,
    FK_USUARIO_ID   UUID NOT NULL,
    CONSTRAINT      FK_POLO_ID FOREIGN KEY (FK_POLO_ID)
    REFERENCES      polo (ID) ON DELETE CASCADE,
    CONSTRAINT      FK_USUARIO_ID FOREIGN KEY (FK_USUARIO_ID)
    REFERENCES      usuario (ID) ON DELETE CASCADE
);

CREATE TYPE tipo_doc AS ENUM ('CPF','CNPJ');
CREATE TYPE tipo_origem AS ENUM ('EQUIPAMENTO','PRODUTO','RECURSO');

CREATE TABLE origem
(
    ID SERIAL PRIMARY KEY,
    NOTA_FISCAL VARCHAR(255) NOT NULL,
    CPF_CNPJ_ORIGEM VARCHAR(14) NOT NULL,
    TIPO_DOC tipo_doc NOT NULL,
    DATA TIMESTAMP NOT NULL,
    TIPO_ORIGEM tipo_origem NOT NULL,
    FK_ALVO_ID UUID NOT NULL
);